package com.godaddy.ans.sdk.pop;

public enum ErrorType {
    MALFORMED_PROOF,
    UNSUPPORTED_ALG,
    HTTP_BINDING_MISMATCH,
    PROOF_STALE,
    REPLAY,
    REPLAY_CACHE_FULL,
    SIGNATURE_INVALID,
    CERT_INVALID,
    KEY_MISMATCH,
    TOKEN_BINDING_MISMATCH,
    BINDING_FAILED,
    STATUS_INVALID,
    RECEIPT_INVALID,
    MISSING_HEADERS,
    SCITT_HEADER_INVALID,
    MISCONFIGURED,
    EXPECTED_PEER_MISMATCH
}
